---

- name: Disable hostkey for ansible
  ansible.builtin.shell: >
    [[ ! -f ansible/ansible.cfg ]] || sed -i "s;#host_key_checking = False;host_key_checking = False;" /etc/ansible/ansible.cfg;
  args:
    executable: /bin/bash
  changed_when: false

...
