---

- name: Install pip
  become: true
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true
    force: true

- name: Install ansible
  become: true
  ansible.builtin.pip:
    name: ansible
    version: 7.5.0
  notify: Disable hostkey for ansible

...
