---

- name: Add an apt signing key for Azure-cli
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: yes

- name: Adding apt repository for Azure-cli
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/azure-cli/ jammy main
    state: present
    filename: azure-cli.list
  become: yes

- name: Install azure-cli binaries
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages: 
      - azure-cli
  become: yes
