---

- name: Add an apt signing key for Azure-cli
  become: true
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Adding apt repository for Azure-cli
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main
    state: present
    filename: azure-cli.list

- name: Install azure-cli binaries
  become: true
  ansible.builtin.apt:
    name: azure-cli
    state: present
    update_cache: true

...
