---

- name: Ensure /usr/local/bin exist
  become: true
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    mode: '0755'

- name: Get terraform binary file and unarchive it on the bin folder
  become: true
  ansible.builtin.unarchive:
    src: "{{ devtools_tf_download_url }}"
    dest: /usr/local/bin
    mode: '0755'
    remote_src: true

...
