---

- name: check if newer install
  stat:
    path: ~/.ansible_devtools
  register: new_install

- name: Download terraform
  get_url:
    url: https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
    dest: /tmp/terraform.zip
  when: not new_install.stat.exists

- name: Install unzip
  apt: name=unzip state=present update_cache=true force=yes
  become: yes

- name: Install terraform
  shell: >
    cd /tmp;
    unzip terraform.zip;
    mv terraform /usr/bin/;
    chmod +x /usr/bin/terraform;
  args:
    executable: /bin/bash
  become: yes
  when: not new_install.stat.exists
