---

- name: Add an apt signing key for Helm
  become: true
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Adding apt repository for Helm
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
    filename: helm.list

- name: Install helm binaries
  become: true
  ansible.builtin.apt:
    name: helm
    state: present
    update_cache: true

...
