---

- import_tasks: packages.yml

- import_tasks: azcli.yml

- import_tasks: powerlinefonts.yml

- import_tasks: hashicorp.yml

- import_tasks: kubectl.yml

- import_tasks: helm.yml

- import_tasks: binaries.yml

- import_tasks: endtools.yml
