---

- name: Create folder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/powerlinefonts"
    state: directory
    mode: '0750'

- name: Deploy repos
  ansible.builtin.git:
    repo: https://github.com/powerline/fonts.git
    dest: "{{ ansible_env.HOME }}/powerlinefonts"
    version: "e80e3eba9091dac0655a0a77472e10f53e754bb0"

- name: Install fonts
  ansible.builtin.shell: |
    ./install.sh
    touch "{{ ansible_env.HOME }}/.powerline_installed"
  args:
    creates: "{{ ansible_env.HOME }}/.powerline_installed"
    chdir: "{{ ansible_env.HOME }}/powerlinefonts/"

...
