---

- name: check if newer install
  stat:
    path: ~/.ansible_devtools
  register: new_install

- name: Deploy repos
  git:
    repo: https://github.com/powerline/fonts.git
    dest: /tmp/powerlinefonts
  when: not new_install.stat.exists

- name: Install fonts
  shell: ./install.sh
  args:
    chdir: /tmp/powerlinefonts/
  when: not new_install.stat.exists
