---

dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/ricofehr/ansible:0.2-${MOLECULE_ARCH:-amd64}
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
verifier:
  name: ansible

...
