---

- name: Install a VM for Devops and deployment topics
  hosts: all
  gather_facts: true

  roles:
    - role: base
      tags: ['install']
    - role: oh-my-zsh
      tags: ['install']
    - role: vim
      tags: ['devtool']
    - role: ansible
      tags: ['devtool']
    - role: devtools
      tags: ['devtool', 'osx']
    - role: git
      become: true
      tags: ['devtool', 'git']
    - role: gitconfig
      tags: ['devtool', 'git']

  pre_tasks:
    - name: Stop package managers
      become: true
      ansible.builtin.shell: >
        while fuser /var/lib/apt/lists/lock; do sleep 1; done;
        while fuser /var/cache/apt/archives/lock; do sleep 1; done;
        while fuser /var/lib/dpkg/lock; do sleep 1; done;
        sed -i 's/0/1/' /etc/apt/apt.conf.d/10periodic;
        sed -i 's/0/1/' /etc/apt/apt.conf.d/20auto-upgrades;
        sed -i 's/^Prompt=.*$/Prompt=never/' /etc/update-manager/release-upgrades;
        systemctl disable apt-daily.service;
        systemctl disable apt-daily.timer;
        sleep 2;
      args:
        executable: /bin/bash
      changed_when: false

...
